version: "3.8"

services:
  app:
    build:
      context: .  
      dockerfile: docker/php/Dockerfile  
    image: php-project_app
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www
    networks:
      - lumen_network

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx  

    depends_on:
      - app
    networks:
      - lumen_network

networks:
  lumen_network: